import type { Part } from "@/types/part";

export interface BOMPart {
  id: string;
  name: string;
  specSummary: string;
  qtyNeeded: number;
  matches: Part[];
}

export const MOCK_BOM_PARTS: BOMPart[] = [
  {
    id: "p1",
    name: "M3 × 8mm Socket Head Cap Screw",
    specSummary: "18-8 Stainless Steel · DIN 912 · Socket Drive",
    qtyNeeded: 120,
    matches: [
      {
        mpn: "91290A113",
        manufacturer: "McMaster-Carr",
        description: "M3 × 8mm Socket Head Cap Screw, 18-8 Stainless Steel",
        distributor: "McMaster-Carr",
        distributorSku: "91290A113",
        distributorUrl: "https://www.mcmaster.com/91290A113",
        unitPrice: 0.041,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.041, currency: "USD" },
          { quantity: 100, unitPrice: 0.034, currency: "USD" },
          { quantity: 500, unitPrice: 0.026, currency: "USD" },
        ],
        stockQty: 9999,
        leadTimeDays: 1,
        datasheetUrl: null,
        category: "Fasteners",
        source: "nexar",
      },
      {
        mpn: "H703-ND",
        manufacturer: "Pan Pacific",
        description: "M3 × 8mm Pan Head Phillips Screw, Stainless",
        distributor: "DigiKey",
        distributorSku: "H703-ND",
        distributorUrl: "https://www.digikey.com",
        unitPrice: 0.063,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.063, currency: "USD" },
          { quantity: 50, unitPrice: 0.052, currency: "USD" },
          { quantity: 100, unitPrice: 0.044, currency: "USD" },
        ],
        stockQty: 5400,
        leadTimeDays: 2,
        datasheetUrl: null,
        category: "Fasteners",
        source: "nexar",
      },
      {
        mpn: "91290A113-M",
        manufacturer: "Würth Elektronik",
        description: "M3 × 8mm Socket Head Screw, A2 Stainless",
        distributor: "Mouser",
        distributorSku: "710-7380830800",
        distributorUrl: "https://www.mouser.com",
        unitPrice: 0.057,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.057, currency: "USD" },
          { quantity: 100, unitPrice: 0.045, currency: "USD" },
          { quantity: 500, unitPrice: 0.033, currency: "USD" },
        ],
        stockQty: 2800,
        leadTimeDays: 3,
        datasheetUrl: null,
        category: "Fasteners",
        source: "nexar",
      },
    ],
  },
  {
    id: "p2",
    name: "M3 Hex Nut",
    specSummary: "18-8 Stainless Steel · DIN 934 · 0.5mm Pitch",
    qtyNeeded: 120,
    matches: [
      {
        mpn: "90592A085",
        manufacturer: "McMaster-Carr",
        description: "M3 × 0.5mm Hex Nut, 18-8 Stainless",
        distributor: "McMaster-Carr",
        distributorSku: "90592A085",
        distributorUrl: "https://www.mcmaster.com/90592A085",
        unitPrice: 0.022,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.022, currency: "USD" },
          { quantity: 100, unitPrice: 0.018, currency: "USD" },
          { quantity: 500, unitPrice: 0.013, currency: "USD" },
        ],
        stockQty: 9999,
        leadTimeDays: 1,
        datasheetUrl: null,
        category: "Fasteners",
        source: "nexar",
      },
      {
        mpn: "H507-ND",
        manufacturer: "Pan Pacific",
        description: "M3 Hex Nut Stainless Steel",
        distributor: "DigiKey",
        distributorSku: "H507-ND",
        distributorUrl: "https://www.digikey.com",
        unitPrice: 0.031,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.031, currency: "USD" },
          { quantity: 100, unitPrice: 0.024, currency: "USD" },
        ],
        stockQty: 3200,
        leadTimeDays: 2,
        datasheetUrl: null,
        category: "Fasteners",
        source: "nexar",
      },
    ],
  },
  {
    id: "p3",
    name: "M3 × 5mm Female Brass Standoff",
    specSummary: "Brass · M3 Female-Female · 5mm Length",
    qtyNeeded: 32,
    matches: [
      {
        mpn: "970050244",
        manufacturer: "Würth Elektronik",
        description: "M3 × 5mm Brass Female Standoff",
        distributor: "DigiKey",
        distributorSku: "732-970050244-ND",
        distributorUrl: "https://www.digikey.com",
        unitPrice: 0.28,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.28, currency: "USD" },
          { quantity: 10, unitPrice: 0.22, currency: "USD" },
          { quantity: 50, unitPrice: 0.17, currency: "USD" },
        ],
        stockQty: 4100,
        leadTimeDays: 2,
        datasheetUrl: null,
        category: "Fasteners",
        source: "nexar",
      },
      {
        mpn: "24305",
        manufacturer: "Keystone",
        description: "M3 × 5mm Brass Hex Standoff F-F",
        distributor: "Mouser",
        distributorSku: "534-24305",
        distributorUrl: "https://www.mouser.com",
        unitPrice: 0.31,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.31, currency: "USD" },
          { quantity: 10, unitPrice: 0.25, currency: "USD" },
          { quantity: 100, unitPrice: 0.19, currency: "USD" },
        ],
        stockQty: 1850,
        leadTimeDays: 3,
        datasheetUrl: null,
        category: "Fasteners",
        source: "nexar",
      },
      {
        mpn: "9900-M3-5",
        manufacturer: "RAF",
        description: "M3 × 5mm Unthreaded Hex Standoff, Brass",
        distributor: "Arrow",
        distributorSku: "9900-M3-5",
        distributorUrl: "https://www.arrow.com",
        unitPrice: 0.25,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.25, currency: "USD" },
          { quantity: 50, unitPrice: 0.19, currency: "USD" },
          { quantity: 100, unitPrice: 0.15, currency: "USD" },
        ],
        stockQty: 900,
        leadTimeDays: 5,
        datasheetUrl: null,
        category: "Fasteners",
        source: "nexar",
      },
    ],
  },
  {
    id: "p4",
    name: "JST-PH 2-Pin Right-Angle Connector",
    specSummary: "2.0mm Pitch · Right Angle · Through-Hole",
    qtyNeeded: 24,
    matches: [
      {
        mpn: "B2B-PH-K-S",
        manufacturer: "JST",
        description: "JST PH Series 2-Pin Right Angle Header, 2.0mm",
        distributor: "DigiKey",
        distributorSku: "455-1719-ND",
        distributorUrl: "https://www.digikey.com",
        unitPrice: 0.17,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.17, currency: "USD" },
          { quantity: 10, unitPrice: 0.13, currency: "USD" },
          { quantity: 100, unitPrice: 0.098, currency: "USD" },
        ],
        stockQty: 22000,
        leadTimeDays: 0,
        datasheetUrl: "https://www.jst.com",
        category: "Connectors",
        source: "nexar",
      },
      {
        mpn: "B2B-PH-K-S",
        manufacturer: "JST",
        description: "JST PH 2-Pin RA PCB Connector",
        distributor: "Mouser",
        distributorSku: "474-B2B-PH-K-S",
        distributorUrl: "https://www.mouser.com",
        unitPrice: 0.19,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.19, currency: "USD" },
          { quantity: 10, unitPrice: 0.15, currency: "USD" },
          { quantity: 100, unitPrice: 0.11, currency: "USD" },
        ],
        stockQty: 8500,
        leadTimeDays: 1,
        datasheetUrl: null,
        category: "Connectors",
        source: "nexar",
      },
    ],
  },
  {
    id: "p5",
    name: "LM358DR Dual Op-Amp",
    specSummary: "Texas Instruments · 1MHz · ±16V · SOIC-8",
    qtyNeeded: 48,
    matches: [
      {
        mpn: "LM358DR",
        manufacturer: "Texas Instruments",
        description: "Dual General-Purpose Op-Amp, 1MHz, ±16V, SOIC-8",
        distributor: "DigiKey",
        distributorSku: "296-1395-1-ND",
        distributorUrl: "https://www.digikey.com",
        unitPrice: 0.167,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.167, currency: "USD" },
          { quantity: 10, unitPrice: 0.132, currency: "USD" },
          { quantity: 100, unitPrice: 0.089, currency: "USD" },
          { quantity: 1000, unitPrice: 0.062, currency: "USD" },
        ],
        stockQty: 42850,
        leadTimeDays: 0,
        datasheetUrl: "https://www.ti.com/lit/ds/symlink/lm358.pdf",
        category: "Integrated Circuits",
        source: "nexar",
      },
      {
        mpn: "LM358DR",
        manufacturer: "Texas Instruments",
        description: "Dual General-Purpose Op-Amp, 1MHz, ±16V, SOIC-8",
        distributor: "Mouser",
        distributorSku: "595-LM358DR",
        distributorUrl: "https://www.mouser.com",
        unitPrice: 0.18,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.18, currency: "USD" },
          { quantity: 10, unitPrice: 0.141, currency: "USD" },
          { quantity: 100, unitPrice: 0.097, currency: "USD" },
        ],
        stockQty: 31200,
        leadTimeDays: 0,
        datasheetUrl: null,
        category: "Integrated Circuits",
        source: "nexar",
      },
      {
        mpn: "LM358ADR",
        manufacturer: "Texas Instruments",
        description: "Dual Op-Amp Extended Temp, SOIC-8",
        distributor: "Arrow",
        distributorSku: "LM358ADR",
        distributorUrl: "https://www.arrow.com",
        unitPrice: 0.234,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.234, currency: "USD" },
          { quantity: 25, unitPrice: 0.189, currency: "USD" },
          { quantity: 100, unitPrice: 0.142, currency: "USD" },
        ],
        stockQty: 8740,
        leadTimeDays: 3,
        datasheetUrl: null,
        category: "Integrated Circuits",
        source: "nexar",
      },
    ],
  },
  {
    id: "p6",
    name: "10kΩ Thick Film Resistor 0402",
    specSummary: "Yageo · ±1% · 62.5mW · 0402 Package",
    qtyNeeded: 500,
    matches: [
      {
        mpn: "RC0402FR-0710KL",
        manufacturer: "Yageo",
        description: "10kΩ ±1% 62.5mW Thick Film Resistor, 0402",
        distributor: "DigiKey",
        distributorSku: "311-10.0KHRCT-ND",
        distributorUrl: "https://www.digikey.com",
        unitPrice: 0.01,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.01, currency: "USD" },
          { quantity: 100, unitPrice: 0.00295, currency: "USD" },
          { quantity: 1000, unitPrice: 0.00161, currency: "USD" },
          { quantity: 5000, unitPrice: 0.00116, currency: "USD" },
        ],
        stockQty: 2100000,
        leadTimeDays: 0,
        datasheetUrl: "https://www.yageo.com",
        category: "Resistors",
        source: "nexar",
      },
      {
        mpn: "RC0402FR-0710KL",
        manufacturer: "Yageo",
        description: "10kΩ ±1% 62.5mW Thick Film Resistor, 0402",
        distributor: "Mouser",
        distributorSku: "603-RC0402FR-0710KL",
        distributorUrl: "https://www.mouser.com",
        unitPrice: 0.011,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.011, currency: "USD" },
          { quantity: 100, unitPrice: 0.00332, currency: "USD" },
          { quantity: 1000, unitPrice: 0.00183, currency: "USD" },
        ],
        stockQty: 4850000,
        leadTimeDays: 0,
        datasheetUrl: null,
        category: "Resistors",
        source: "nexar",
      },
    ],
  },
  {
    id: "p7",
    name: "100nF MLCC Capacitor 0603",
    specSummary: "Murata · X7R · ±10% · 16V · 0603",
    qtyNeeded: 800,
    matches: [
      {
        mpn: "GRM188R71C104KA01D",
        manufacturer: "Murata",
        description: "100nF ±10% 16V X7R Ceramic Capacitor, 0603",
        distributor: "DigiKey",
        distributorSku: "490-1532-1-ND",
        distributorUrl: "https://www.digikey.com",
        unitPrice: 0.01,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.01, currency: "USD" },
          { quantity: 100, unitPrice: 0.00295, currency: "USD" },
          { quantity: 1000, unitPrice: 0.00177, currency: "USD" },
          { quantity: 5000, unitPrice: 0.00139, currency: "USD" },
        ],
        stockQty: 1200000,
        leadTimeDays: 0,
        datasheetUrl: "https://www.murata.com",
        category: "Capacitors",
        source: "nexar",
      },
      {
        mpn: "C0603C104K4RACTU",
        manufacturer: "KEMET",
        description: "100nF ±10% 16V X7R 0603 Ceramic Cap",
        distributor: "Mouser",
        distributorSku: "80-C0603C104K4RACTU",
        distributorUrl: "https://www.mouser.com",
        unitPrice: 0.012,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.012, currency: "USD" },
          { quantity: 100, unitPrice: 0.0035, currency: "USD" },
          { quantity: 1000, unitPrice: 0.002, currency: "USD" },
        ],
        stockQty: 580000,
        leadTimeDays: 1,
        datasheetUrl: null,
        category: "Capacitors",
        source: "nexar",
      },
    ],
  },
  {
    id: "p8",
    name: "USB-C Receptacle 16-Pin",
    specSummary: "Mid-Mount 0.8mm · SMD · USB 2.0 Compatible",
    qtyNeeded: 16,
    matches: [
      {
        mpn: "USB4135-GF-A",
        manufacturer: "GCT",
        description: "USB Type C Receptacle, 16-Pin, SMD Mid-Mount 0.8mm",
        distributor: "DigiKey",
        distributorSku: "2073-USB4135-GF-A-ND",
        distributorUrl: "https://www.digikey.com",
        unitPrice: 0.74,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.74, currency: "USD" },
          { quantity: 10, unitPrice: 0.61, currency: "USD" },
          { quantity: 100, unitPrice: 0.48, currency: "USD" },
        ],
        stockQty: 12400,
        leadTimeDays: 0,
        datasheetUrl: null,
        category: "Connectors",
        source: "nexar",
      },
      {
        mpn: "CX90B1-16P",
        manufacturer: "Amphenol",
        description: "USB Type-C 16-Pin Receptacle, SMD, Bottom Mount",
        distributor: "Mouser",
        distributorSku: "523-CX90B1-16P",
        distributorUrl: "https://www.mouser.com",
        unitPrice: 0.82,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.82, currency: "USD" },
          { quantity: 10, unitPrice: 0.68, currency: "USD" },
          { quantity: 100, unitPrice: 0.54, currency: "USD" },
        ],
        stockQty: 5200,
        leadTimeDays: 2,
        datasheetUrl: null,
        category: "Connectors",
        source: "nexar",
      },
      {
        mpn: "10137062-00021LF",
        manufacturer: "Amphenol FCI",
        description: "USB Type C 16-Pin SMD Receptacle",
        distributor: "Arrow",
        distributorSku: "10137062-00021LF",
        distributorUrl: "https://www.arrow.com",
        unitPrice: 0.69,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.69, currency: "USD" },
          { quantity: 25, unitPrice: 0.56, currency: "USD" },
          { quantity: 100, unitPrice: 0.44, currency: "USD" },
        ],
        stockQty: 3100,
        leadTimeDays: 4,
        datasheetUrl: null,
        category: "Connectors",
        source: "nexar",
      },
    ],
  },
  {
    id: "p9",
    name: "2×5 2.54mm Male Pin Header",
    specSummary: "Through-Hole · Straight · Gold Flash",
    qtyNeeded: 40,
    matches: [
      {
        mpn: "67996-210HLF",
        manufacturer: "Amphenol FCI",
        description: "2×5 2.54mm Pitch Double Row Male Header, TH Straight",
        distributor: "DigiKey",
        distributorSku: "609-4864-ND",
        distributorUrl: "https://www.digikey.com",
        unitPrice: 0.42,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.42, currency: "USD" },
          { quantity: 10, unitPrice: 0.34, currency: "USD" },
          { quantity: 100, unitPrice: 0.25, currency: "USD" },
        ],
        stockQty: 18700,
        leadTimeDays: 0,
        datasheetUrl: null,
        category: "Connectors",
        source: "nexar",
      },
      {
        mpn: "M20-9981046",
        manufacturer: "Harwin",
        description: "2×5 2.54mm Male Header, Straight, Gold",
        distributor: "Mouser",
        distributorSku: "855-M20-9981046",
        distributorUrl: "https://www.mouser.com",
        unitPrice: 0.47,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.47, currency: "USD" },
          { quantity: 10, unitPrice: 0.39, currency: "USD" },
          { quantity: 100, unitPrice: 0.29, currency: "USD" },
        ],
        stockQty: 9300,
        leadTimeDays: 1,
        datasheetUrl: null,
        category: "Connectors",
        source: "nexar",
      },
    ],
  },
  {
    id: "p10",
    name: "470Ω Thick Film Resistor 0402",
    specSummary: "Yageo · ±1% · 62.5mW · 0402 Package",
    qtyNeeded: 200,
    matches: [
      {
        mpn: "RC0402FR-07470RL",
        manufacturer: "Yageo",
        description: "470Ω ±1% 62.5mW Thick Film Resistor, 0402",
        distributor: "DigiKey",
        distributorSku: "311-470HRCT-ND",
        distributorUrl: "https://www.digikey.com",
        unitPrice: 0.01,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.01, currency: "USD" },
          { quantity: 100, unitPrice: 0.00295, currency: "USD" },
          { quantity: 1000, unitPrice: 0.00161, currency: "USD" },
        ],
        stockQty: 3400000,
        leadTimeDays: 0,
        datasheetUrl: null,
        category: "Resistors",
        source: "nexar",
      },
      {
        mpn: "RC0402FR-07470RL",
        manufacturer: "Yageo",
        description: "470Ω ±1% 0402 Resistor",
        distributor: "Mouser",
        distributorSku: "603-RC0402FR-07470RL",
        distributorUrl: "https://www.mouser.com",
        unitPrice: 0.011,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.011, currency: "USD" },
          { quantity: 100, unitPrice: 0.00332, currency: "USD" },
          { quantity: 1000, unitPrice: 0.00183, currency: "USD" },
        ],
        stockQty: 2200000,
        leadTimeDays: 0,
        datasheetUrl: null,
        category: "Resistors",
        source: "nexar",
      },
    ],
  },
  {
    id: "p11",
    name: "M4 × 12mm Button Head Screw",
    specSummary: "316 Stainless Steel · ISO 7380 · Hex Socket",
    qtyNeeded: 64,
    matches: [
      {
        mpn: "92095A195",
        manufacturer: "McMaster-Carr",
        description: "M4 × 12mm Button Head Socket Cap Screw, 316 SS",
        distributor: "McMaster-Carr",
        distributorSku: "92095A195",
        distributorUrl: "https://www.mcmaster.com/92095A195",
        unitPrice: 0.076,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.076, currency: "USD" },
          { quantity: 50, unitPrice: 0.061, currency: "USD" },
          { quantity: 200, unitPrice: 0.048, currency: "USD" },
        ],
        stockQty: 9999,
        leadTimeDays: 1,
        datasheetUrl: null,
        category: "Fasteners",
        source: "nexar",
      },
      {
        mpn: "H807-ND",
        manufacturer: "Pan Pacific",
        description: "M4 × 12mm Button Head Screw SS",
        distributor: "DigiKey",
        distributorSku: "H807-ND",
        distributorUrl: "https://www.digikey.com",
        unitPrice: 0.091,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.091, currency: "USD" },
          { quantity: 50, unitPrice: 0.074, currency: "USD" },
        ],
        stockQty: 2100,
        leadTimeDays: 2,
        datasheetUrl: null,
        category: "Fasteners",
        source: "nexar",
      },
    ],
  },
  {
    id: "p12",
    name: "10µF Electrolytic Capacitor 0805",
    specSummary: "Murata · X5R · ±20% · 10V · 0805",
    qtyNeeded: 300,
    matches: [
      {
        mpn: "GRM21BR61A106KE18L",
        manufacturer: "Murata",
        description: "10µF ±20% 10V X5R Ceramic Capacitor, 0805",
        distributor: "DigiKey",
        distributorSku: "490-3896-1-ND",
        distributorUrl: "https://www.digikey.com",
        unitPrice: 0.043,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.043, currency: "USD" },
          { quantity: 100, unitPrice: 0.015, currency: "USD" },
          { quantity: 1000, unitPrice: 0.009, currency: "USD" },
        ],
        stockQty: 640000,
        leadTimeDays: 0,
        datasheetUrl: null,
        category: "Capacitors",
        source: "nexar",
      },
      {
        mpn: "CL21A106KAYNNNE",
        manufacturer: "Samsung",
        description: "10µF ±10% 10V X5R 0805 Ceramic Cap",
        distributor: "Mouser",
        distributorSku: "187-CL21A106KAYNNNE",
        distributorUrl: "https://www.mouser.com",
        unitPrice: 0.038,
        currency: "USD",
        priceBreaks: [
          { quantity: 1, unitPrice: 0.038, currency: "USD" },
          { quantity: 100, unitPrice: 0.013, currency: "USD" },
          { quantity: 1000, unitPrice: 0.0078, currency: "USD" },
        ],
        stockQty: 920000,
        leadTimeDays: 0,
        datasheetUrl: null,
        category: "Capacitors",
        source: "nexar",
      },
    ],
  },
];
